language: ruby

rvm:
- 1.9.3

before_script:
  - cp config/database.sqlite3.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
